### ISSUE TITLE
Scalable key is invalid in chrome canary

### ISSUE THREAD

**Issue by ghost** [jamestalmage/gh-nag#4]
On Chrome Version 50.0.2640.0 canary (64-bit)

![image](https://cloud.githubusercontent.com/assets/8956796/12814000/c1cf5f10-cb4c-11e5-97a9-63da815b0281.png)

**Comment by jamestalmage** [comment]
OK. Does just deleting that line work? Happy to accept a PR if you verify it works

**Comment by ghost** [comment]
Yes, without `scalable` extension works.

In chrome and firefox icon key should be a number and icon should not be svg.
